services:
  front:
    env_file:
      - .env
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    volumes:
      - ./front:/front
      - node_modules:/front/node_modules
    ports:
      - 5173:5173
    tty: true
    depends_on:
      - db
  

  api:
    env_file:
      - .env
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - ./api:/api
    ports:
     - 8080:8080
    tty: true
    depends_on:
      - db
    networks:
      - translate_memo_networks

  db:
    image: mysql:8.2.0
    container_name: db
    tty: true
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - translate_memo_networks

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/front/node_modules
      o: bind
  db:

networks:
  translate_memo_networks:
    external: true